version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase and Logging in to AWS ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 213375652280.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "Starting build phase and Building Docker image 'brain-task-app:latest'..."
      - docker build -t brain-task-app:latest .
      - echo "Tagging image for ECR as 'brain-task-app:4'..."
      - docker tag brain-task-app:latest 213375652280.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest
      - echo "Starting post-build phase and Pushing Docker image to ECR..."
      - docker push 213375652280.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest
      - echo "Docker image pushed successfully to 213375652280.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:4"
  post_build:
    commands:
      - echo "Checking Kubernetes manifests.."
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 213375652280.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Setting up kubeconfig for EKS cluster Mindtrack..."
      - aws eks update-kubeconfig --region ap-south-1 --name Mindtrack
      - echo "Using existing Docker image from ECR brain-task-app-latest"
      - docker pull 213375652280.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f deployment.yaml --validate=false
      - kubectl apply -f service.yaml --validate=false
      - echo "Deployment to EKS cluster Mindtrack complete!"
      - echo "Waiting for LoadBalancer DNS..."
      - |
        for i in {1..20}; do
          DNS=$(kubectl get svc brain-task-service \
          -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          if [ -n "$DNS" ]; then
            echo "DNS found!"
            break
          fi
          echo "Waiting for DNS... retry $i"
          sleep 15
        done

      - echo "APPLICATION DNS"
      - echo "http://$DNS:3000"
